CREATE OR REPLACE PROCEDURE PA_NMI_HORAS_GUARDAR_SALIDA(
    P_IN_HRS_Codigo IN NMI_HORAS.HRS_Codigo%TYPE,
    P_IN_HRS_Hora_Salida IN VARCHAR
) IS
BEGIN
    SAVEPOINT PS_AN_HORAS_GUARDAR_SALIDA;
    UPDATE NMI_HORAS SET
        HRS_Hora_Salida = TO_TIMESTAMP(P_IN_HRS_Hora_Salida, 'DD-MM-YYYY HH24:MI')
            WHERE HRS_Codigo = P_IN_HRS_Codigo;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK TO SAVEPOINT PS_AN_HORAS_GUARDAR_SALIDA;
END PA_NMI_HORAS_GUARDAR_SALIDA;
/