CREATE OR REPLACE PROCEDURE PA_NMI_HORAS_GUARDAR_ENTRADA(
    P_IN_EPU_Codigo IN NMI_HORAS.EPU_Codigo%TYPE,
    P_IN_HRS_Hora_Entrada IN VARCHAR,
    P_OUT_HRS_Codigo OUT NMI_HORAS.HRS_Codigo%TYPE
) IS
BEGIN
    SAVEPOINT PS_AN_HORAS_GUARDAR_ENTRADA;
    INSERT INTO NMI_HORAS (EPU_Codigo, HRS_Hora_Entrada)
        VALUES (P_IN_EPU_Codigo, TO_TIMESTAMP(P_IN_HRS_Hora_Entrada, 'DD-MM-YYYY HH24:MI'))
        RETURNING HRS_Codigo INTO P_OUT_HRS_Codigo;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK TO SAVEPOINT PS_AN_HORAS_GUARDAR_ENTRADA;
END PA_NMI_HORAS_GUARDAR_ENTRADA;
/