CREATE OR REPLACE FUNCTION FN_OBTENER_TODO_TIPOS_MONEDA
    RETURN SYS_REFCURSOR
    IS
    CUR_REGISTROS SYS_REFCURSOR;
BEGIN
OPEN CUR_REGISTROS FOR
SELECT TMO_CODIGO,
       TMO_NOMBRE,
       TMO_SIMBOLO,
       TMO_TASA_CAMBIO,
       TMO_ESTADO
FROM NMI_TIPO_MONEDA;
RETURN CUR_REGISTROS;
END;
/


