CREATE OR REPLACE FUNCTION FN_OBTENER_TIPO_MONEDA_POR_ID(
    P_IN_TMO_CODIGO IN NMI_TIPO_MONEDA.TMO_CODIGO%TYPE
)
    RETURN SYS_REFCURSOR
    IS
    CUR_REGISTROS SYS_REFCURSOR;
BEGIN
OPEN CUR_REGISTROS FOR
SELECT TMO_CODIGO,
       TMO_NOMBRE,
       TMO_SIMBOLO,
       TMO_TASA_CAMBIO,
       TMO_ESTADO
FROM NMI_TIPO_MONEDA
WHERE TMO_CODIGO = P_IN_TMO_CODIGO;
RETURN CUR_REGISTROS;
END;
/

