CREATE OR REPLACE PROCEDURE PA_NMI_TIPO_MONEDA_ELIMINAR(P_IN_TMO_CODIGO IN NMI_TIPO_MONEDA.TMO_CODIGO%TYPE) IS
BEGIN
SAVEPOINT PS_NMI_TIPO_MONEDA_ELIMINAR;
DELETE FROM NMI_TIPO_MONEDA WHERE TMO_CODIGO = P_IN_TMO_CODIGO;
COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK TO SAVEPOINT PS_NMI_TIPO_MONEDA_ELIMINAR;
END PA_NMI_TIPO_MONEDA_ELIMINAR;
/