CREATE OR REPLACE PROCEDURE PA_NMI_TIPO_MONEDA_ACTUALIZAR(
    P_IN_TMO_CODIGO IN NMI_TIPO_MONEDA.TMO_CODIGO%TYPE,
    P_IN_TMO_NOMBRE IN NMI_TIPO_MONEDA.TMO_NOMBRE%TYPE,
    P_IN_TMO_SIMBOLO IN NMI_TIPO_MONEDA.TMO_SIMBOLO%TYPE,
    P_IN_TMO_TASA_CAMBIO IN NMI_TIPO_MONEDA.TMO_TASA_CAMBIO%TYPE,
    P_IN_TMO_ESTADO IN NMI_TIPO_MONEDA.TMO_ESTADO%TYPE
) IS
BEGIN
SAVEPOINT PS_NMI_TIPO_MONEDA_ACTUALIZAR;
UPDATE NMI_TIPO_MONEDA
SET TMO_NOMBRE = P_IN_TMO_NOMBRE,
    TMO_SIMBOLO = P_IN_TMO_SIMBOLO,
    TMO_TASA_CAMBIO = P_IN_TMO_TASA_CAMBIO,
    TMO_ESTADO= P_IN_TMO_ESTADO
WHERE TMO_CODIGO = P_IN_TMO_CODIGO;
COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK TO SAVEPOINT PS_NMI_TIPO_MONEDA_ACTUALIZAR;
END PA_NMI_TIPO_MONEDA_ACTUALIZAR;
/