CREATE OR REPLACE PROCEDURE PA_OBTENER_TIPO_MONEDA_POR_ID(
    P_OUT_CURSOR OUT SYS_REFCURSOR,
    P_IN_TMO_CODIGO IN NMI_TIPO_MONEDA.TMO_CODIGO%TYPE
)
AS
BEGIN
    P_OUT_CURSOR := FN_OBTENER_TIPO_MONEDA_POR_ID(P_IN_TMO_CODIGO);
END;
