CREATE OR REPLACE FUNCTION FN_OBTENER_SUSPENSIONES_POR_ID(
    P_IN_SUS_CODIGO IN NMI_SUSPENSION.SUS_CODIGO%TYPE
)
    RETURN SYS_REFCURSOR
    IS
    CUR_REGISTROS SYS_REFCURSOR;
BEGIN
    OPEN CUR_REGISTROS FOR
SELECT
    S.SUS_CODIGO,
    S.EPU_CODIGO,
    S.TSU_CODIGO,
    S.SUS_FECHA_SALIDA,
    S.SUS_FECHA_REGRESO,
    S.SUS_ESTADO,
    EP.EMP_CODIGO,
    E.EMP_PRIMER_NOMBRE,
    E.EMP_PRIMER_APELLIDO,
    TS.TSU_NOMBRE
FROM NMI_SUSPENSION S INNER JOIN
     NMI_EMPLEADO_PUESTO EP ON A.EPU_CODIGO = EP.EPU_CODIGO
                        INNER JOIN NMI_EMPLEADO E ON EP.EMP_CODIGO = E.EMP_CODIGO,
     NMI_TIPO_SUSPENSION TS
WHERE S.SUS_CODIGO = P_IN_SUS_CODIGO AND
    EP.EPU_ESTADO = 1 AND
    S.TSU_CODIGO = TS.TSU_CODIGO
ORDER BY A.AUS_CODIGO;
RETURN CUR_REGISTROS;
END;
/