CREATE OR REPLACE FUNCTION FN_OBTENER_TODO_SUSPENSIONES
              RETURN SYS_REFCURSOR
IS
        CUR_REGISTROS SYS_REFCURSOR;
BEGIN
    OPEN CUR_REGISTROS FOR
SELECT
    S.SUS_CODIGO,
    S.EPU_CODIGO,
    S.TSU_CODIGO,
    S.SUS_FECHA_SALIDA,
    S.Sus_fecha_regreso,
    S.SUS_ESTADO,
    EP.EMP_CODIGO,
    E.EMP_PRIMER_NOMBRE,
    E.EMP_PRIMER_APELLIDO,
    tS.tSu_nombre
FROM NMI_SUSPENSION S INNER JOIN
     NMI_EMPLEADO_PUESTO EP ON O.EPU_CODIGO = EP.EPU_CODIGO
                        INNER JOIN NMI_EMPLEADO E ON EP.EMP_CODIGO = E.EMP_CODIGO,
     NMI_TIPO_SUSPENSION TS
WHERE EP.EPU_ESTADO = 1 AND
  S.tSu_codigo=tS.tSu_codigo 
ORDER BY A.SUS_CODIGO;
RETURN CUR_REGISTROS;
END;
/