CREATE OR REPLACE FUNCTION FN_OBTENER_NOMBRE_TIPO_SUSPENSION
RETURN SYS_REFCURSOR
IS
    CUR_REGISTROS SYS_REFCURSOR;
BEGIN
    OPEN CUR_REGISTROS FOR
        SELECT  
            TS.TSU_CODIGO,
            TS.TSU_NOMBRE    
        FROM NMI_TIPO_SUSPENSION TS;
    RETURN CUR_REGISTROS;
END;
/