CREATE OR REPLACE FUNCTION FN_OBTENER_LISTADO_SUSPENSION(
    P_IN_SEARCH IN VARCHAR2,
    P_IN_SIZE IN NUMBER,
    P_IN_PAGE IN NUMBER
)
    RETURN SYS_REFCURSOR
    IS
    CUR_REGISTROS SYS_REFCURSOR;
V_NEW_PAGE    NUMBER := 0;
BEGIN
    V_NEW_PAGE := P_IN_PAGE * P_IN_SIZE;
OPEN CUR_REGISTROS FOR
SELECT
    S.SUS_CODIGO,
    S.EPU_CODIGO,
    S.tSu_codigo,
    S.SUS_fecha_salida,
    S.SUS_fecha_regreso,
    S.SUS_ESTADO,
    EP.EMP_CODIGO,
    E.EMP_PRIMER_NOMBRE,
    E.EMP_PRIMER_APELLIDO,
    tS.tSu_nombre
FROM NMI_SUSPENSION S INNER JOIN
     NMI_EMPLEADO_PUESTO EP ON O.EPU_CODIGO = EP.EPU_CODIGO
                        INNER JOIN NMI_EMPLEADO E ON EP.EMP_CODIGO = E.EMP_CODIGO,
     NMI_TIPO_SUSPENSION TS 
WHERE EP.EPU_ESTADO = 1 AND 
    S.tSU_codigo=tS.tSU_codigo AND(
        (P_IN_SEARCH IS NULL OR UPPER(S.SUS_CODIGO) LIKE '%' || UPPER(P_IN_SEARCH) || '%')
        OR (P_IN_SEARCH IS NULL OR UPPER(S.EPU_CODIGO) LIKE '%' || UPPER(P_IN_SEARCH) || '%')
        OR (P_IN_SEARCH IS NULL OR UPPER(S.TSU_CODIGO) LIKE '%' || UPPER(P_IN_SEARCH) || '%')
        OR (P_IN_SEARCH IS NULL OR UPPER(S.Sus_fecha_salida) LIKE '%' || UPPER(P_IN_SEARCH) || '%')
        OR (P_IN_SEARCH IS NULL OR UPPER(S.Sus_fecha_REGRESO) LIKE '%' || UPPER(P_IN_SEARCH) || '%')
        OR (P_IN_SEARCH IS NULL OR UPPER(S.Sus_ESTADO) LIKE '%' || UPPER(P_IN_SEARCH) || '%')
        OR (P_IN_SEARCH IS NULL OR UPPER(EP.EMP_CODIGO) LIKE '%' || UPPER(P_IN_SEARCH) || '%')
        OR (P_IN_SEARCH IS NULL OR UPPER(E.EMP_PRIMER_NOMBRE) LIKE '%' || UPPER(P_IN_SEARCH) || '%')
        OR (P_IN_SEARCH IS NULL OR UPPER(E.EMP_PRIMER_APELLIDO) LIKE '%' || UPPER(P_IN_SEARCH) || '%'))
ORDER BY S.SUS_CODIGO
    OFFSET V_NEW_PAGE ROWS FETCH NEXT P_IN_SIZE ROWS ONLY;
RETURN CUR_REGISTROS;
END;
/