CREATE OR REPLACE PROCEDURE PA_NMI_SUSPENSION_ACTUALIZAR (
    P_IN_CODIGO IN NMI_SUSPENSION.SUS_CODIGO%TYPE,
    P_IN_EPU_CODIGO IN NMI_SUSPENSION.EPU_CODIGO%TYPE,
    P_IN_TAU_CODIGO IN NMI_SUSPENSION.TSU_CODIGO%TYPE,
    P_IN_FECHA_SALIDA IN VARCHAR,
    P_IN_FECHA_REGRESO IN VARCHAR,
    P_IN_ESTADO IN NMI_SUSPENSION.SUS_ESTADO%TYPE
)
AS
BEGIN
    SAVEPOINT PS_AN_ACTUALIZAR_SUSPENSION;
    
    UPDATE NMI_SUSPENSION SET EPU_CODIGO = P_IN_EPU_CODIGO, TSU_CODIGO = P_IN_TSU_CODIGO, 
                            SUS_FECHA_SALIDA = TO_TIMESTAMP(P_IN_FECHA_SALIDA, 'DD-MM-YYYY'), 
                            SUS_FECHA_REGRESO = TO_TIMESTAMP(P_IN_FECHA_REGRESO, 'DD-MM-YYYY'),
                            SUS_ESTADO = P_IN_ESTADO
    WHERE SUS_CODIGO = P_IN_CODIGO;
    
    COMMIT;
EXCEPTION 
    WHEN OTHERS THEN
        ROLLBACK TO PS_AN_ACTUALIZAR_SUSPENSION;
END;
/
