CREATE OR REPLACE PROCEDURE PA_NMI_SUSPENSION_INSERTAR (
    P_IN_EPU_CODIGO IN NMI_SUSPENSION.SUS_CODIGO%TYPE,
    P_IN_TSU_CODIGO IN NMI_SUSPENSION.TSU_CODIGO%TYPE,
    P_IN_FECHA_SALIDA IN VARCHAR,
    P_IN_FECHA_REGRESO IN VARCHAR,
    P_IN_ESTADO IN NMI_SUSPENSION.SUS_ESTADO%TYPE,
    P_OUT_CODIGO OUT NMI_SUSPENSION.SUS_CODIGO%TYPE   
)
AS
BEGIN
    SAVEPOINT PS_AN_INSERTAR_SUSPENSION;
    
    INSERT INTO NMI_SUSPENSION (EPU_CODIGO, TSU_CODIGO, Sus_fecha_salida, Sus_fecha_regreso, sus_estado)
        VALUES(P_IN_EPU_CODIGO,p_in_tSu_codigo, TO_TIMESTAMP(P_IN_FECHA_SALIDA, 'DD-MM-YYYY'), TO_TIMESTAMP(P_IN_FECHA_REGRESO, 'DD-MM-YYYY'), P_IN_ESTADO)
        RETURNING AUS_CODIGO INTO P_OUT_CODIGO;
    
    COMMIT;
EXCEPTION 
    WHEN OTHERS THEN
        ROLLBACK TO PS_AN_INSERTAR_SUSPENSION;
END;
/