CREATE OR REPLACE FUNCTION FN_OBTENER_BONIFICACION_POR_ID_DE_EMPLEADO(
    P_IN_EMP_CODIGO NMI_EMPLEADO.EMP_CODIGO%TYPE,
    P_IN_BON_CODIGO NMI_EMPLEADO_BONIFICACION.BON_CODIGO%TYPE
)
RETURN SYS_REFCURSOR
IS
    CUR_REGISTROS SYS_REFCURSOR;
BEGIN
    OPEN CUR_REGISTROS FOR
          SELECT EP.EMP_CODIGO
          FROM  NMI_EMPLEADO_PUESTO EP,
                NMI_EMPLEADO_BONIFICACION EB
          WHERE EP.EPU_CODIGO = EB.EPU_CODIGO AND
                EP.EMP_CODIGO = P_IN_EMP_CODIGO AND
                EB.BON_CODIGO = P_IN_BON_CODIGO AND
                EB.EBO_ESTADO = 1;
    RETURN CUR_REGISTROS;
END;
/
