CREATE OR REPLACE FUNCTION FN_OBTENER_BONIFICACIONES_QUE_NO_TIENE_EMPLEADO (
    P_IN_EMP_CODIGO NMI_EMPLEADO.EMP_CODIGO%TYPE
)
RETURN SYS_REFCURSOR
IS
    CUR_REGISTROS SYS_REFCURSOR;
BEGIN
    OPEN CUR_REGISTROS FOR
SELECT BO.BON_CODIGO, BO.BON_NOMBRE, BO.BON_DESCRIPCION, BO.BON_MONTO, BO.BON_PORCENTAJE, BO.BON_ESTADO
FROM NMI_BONIFICACION BO
WHERE BO.BON_CODIGO NOT IN (
    SELECT  B.BON_CODIGO
    FROM
        NMI_BONIFICACION B,
        NMI_EMPLEADO_BONIFICACION EB,
        NMI_EMPLEADO_PUESTO EP
    WHERE
        B.BON_CODIGO = EB.BON_CODIGO AND
        EB.EPU_CODIGO = EP.EPU_CODIGO AND
        B.BON_ESTADO = 1 AND
        EP.EMP_CODIGO = P_IN_EMP_CODIGO AND
        EP.EPU_ESTADO = 1
) AND
    BO.BON_ESTADO = 1;

RETURN CUR_REGISTROS;
END;
/