CREATE OR REPLACE PROCEDURE PA_NMI_EMPLEADO_BONIFICACION_INSERTAR (
    P_IN_EMP_CODIGO IN NMI_EMPLEADO_PUESTO.EMP_CODIGO%TYPE,
    P_IN_BON_CODIGO IN NMI_EMPLEADO_BONIFICACION.BON_CODIGO%TYPE,
    P_IN_EBO_ESTADO IN NMI_EMPLEADO_BONIFICACION.EBO_ESTADO%TYPE,
    P_OUT_CODIGO OUT NMI_EMPLEADO_BONIFICACION.EBO_CODIGO%TYPE
)
AS
    V_EPU_CODIGO NMI_EMPLEADO_BONIFICACION.EPU_CODIGO%TYPE;
BEGIN
SAVEPOINT PS_AN_INSERTAR_EMPLEADO_BONIFICACION ;

SELECT EP.EPU_CODIGO INTO V_EPU_CODIGO FROM NMI_EMPLEADO_PUESTO EP WHERE EP.EMP_CODIGO = P_IN_EMP_CODIGO AND EP.EPU_ESTADO = 1;

INSERT INTO NMI_EMPLEADO_BONIFICACION (EPU_CODIGO,BON_CODIGO,EBO_ESTADO)
    VALUES(V_EPU_CODIGO,P_IN_BON_CODIGO,P_IN_EBO_ESTADO)
        RETURNING EBO_CODIGO INTO P_OUT_CODIGO;

COMMIT;
EXCEPTION
    WHEN OTHERS THEN
ROLLBACK TO PS_AN_INSERTAR_EMPLEADO_BONIFICACION ;
END;
/