CREATE OR REPLACE PROCEDURE PA_NMI_EMPLEADO_BONIFICACION_ELIMINAR (
    P_IN_CODIGO IN NMI_EMPLEADO_BONIFICACION.EBO_CODIGO%TYPE
)
AS
BEGIN
SAVEPOINT PS_AN_ELIMINAR_EMPLEADO_BONIFICACION ;

DELETE FROM NMI_EMPLEADO_BONIFICACION WHERE EBO_CODIGO = P_IN_CODIGO;

COMMIT;
EXCEPTION
    WHEN OTHERS THEN
ROLLBACK TO  PS_AN_ELIMINAR_EMPLEADO_BONIFICACION;
END;
/