CREATE OR REPLACE PROCEDURE PA_OBTENER_BONIFICACION_POR_ID_DE_EMPLEADO(
    P_IN_EMP_CODIGO NMI_EMPLEADO.EMP_CODIGO%TYPE,
    P_IN_BON_CODIGO NMI_EMPLEADO_BONIFICACION.BON_CODIGO%TYPE,
    P_OUT_CURSOR OUT SYS_REFCURSOR
  )
AS
BEGIN
    P_OUT_CURSOR := FN_OBTENER_BONIFICACION_POR_ID_DE_EMPLEADO(P_IN_EMP_CODIGO,P_IN_BON_CODIGO);
END;
/
