CREATE OR REPLACE PROCEDURE PA_OBTENER_BONIFICACIONES_QUE_NO_TIENE_EMPLEADO(
    P_IN_EMP_CODIGO NMI_EMPLEADO.EMP_CODIGO%TYPE,
    P_OUT_CURSOR OUT SYS_REFCURSOR
  )
AS
BEGIN
    P_OUT_CURSOR := FN_OBTENER_BONIFICACIONES_QUE_NO_TIENE_EMPLEADO(P_IN_EMP_CODIGO);
END;
/