CREATE OR REPLACE FUNCTION FN_OBTENER_TODO_DEPARTAMENTOS
    RETURN SYS_REFCURSOR
    IS
    CUR_REGISTROS SYS_REFCURSOR;
BEGIN
    OPEN CUR_REGISTROS FOR
        SELECT DEP_CODIGO,
               DEP_NOMBRE,
               DEP_DESCRIPCION
        FROM NMI_DEPARTAMENTO;
    RETURN CUR_REGISTROS;
END;
/


