CREATE OR REPLACE FUNCTION FN_OBTENER_DEPARTAMENTO_POR_ID(
    P_IN_DEP_CODIGO IN NMI_DEPARTAMENTO.DEP_CODIGO%TYPE
)
    RETURN SYS_REFCURSOR
    IS
    CUR_REGISTROS SYS_REFCURSOR;
BEGIN
    OPEN CUR_REGISTROS FOR
        SELECT DEP_CODIGO,
               DEP_NOMBRE,
               DEP_DESCRIPCION
        FROM NMI_DEPARTAMENTO
        WHERE DEP_CODIGO = P_IN_DEP_CODIGO;
    RETURN CUR_REGISTROS;
END; /