CREATE OR REPLACE PROCEDURE PA_NMI_DEPARTAMENTO_ELIMINAR(
    P_IN_DEP_CODIGO IN NMI_DEPARTAMENTO.DEP_CODIGO%TYPE
) IS
BEGIN
    SAVEPOINT PS_AN_DEPARTAMENTO_ELIMINAR;
    DELETE FROM nmi_departamento WHERE dep_codigo = P_IN_DEP_CODIGO;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error al eliminar el departamento:');
        ROLLBACK TO SAVEPOINT PS_AN_DEPARTAMENTO_ELIMINAR;
END PA_NMI_DEPARTAMENTO_ELIMINAR;
/