CREATE OR REPLACE PROCEDURE PA_NMI_DEPARTAMENTO_GUARDAR(
    P_IN_DEP_NOMBRE IN NMI_DEPARTAMENTO.DEP_NOMBRE%TYPE,
    P_IN_DEP_DESCRIPCION IN NMI_DEPARTAMENTO.DEP_DESCRIPCION%TYPE,
    P_OUT_DEP_CODIGO OUT NMI_DEPARTAMENTO.DEP_CODIGO%TYPE
) IS
BEGIN
    SAVEPOINT PS_AN_DEPARTAMENTO_GUARDAR;
        INSERT INTO nmi_departamento (dep_nombre, dep_descripcion) VALUES (P_IN_DEP_NOMBRE, P_IN_DEP_DESCRIPCION)
        RETURNING dep_codigo INTO P_OUT_DEP_CODIGO;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK TO SAVEPOINT PS_AN_DEPARTAMENTO_GUARDAR;
END PA_NMI_DEPARTAMENTO_GUARDAR;
/