CREATE OR REPLACE PROCEDURE PA_NMI_EMPLEADO_DESHABILITAR(
    P_IN_EMP_Codigo IN NMI_EMPLEADO_PUESTO.EMP_Codigo%TYPE
) IS
BEGIN
    SAVEPOINT PS_AN_EMPLEADO_DESHABILITAR;
    UPDATE NMI_EMPLEADO_PUESTO
        SET
        EPU_Estado = 0
            WHERE EMP_Codigo = P_IN_EMP_Codigo;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK TO SAVEPOINT PS_AN_EMPLEADO_DESHABILITAR;
END PA_NMI_EMPLEADO_DESHABILITAR;
/