CREATE OR REPLACE PROCEDURE PA_OBTENER_EMPLEADO_POR_ID(
    P_OUT_CURSOR OUT SYS_REFCURSOR,
    P_IN_EMP_Codigo IN NMI_EMPLEADO.EMP_Codigo%TYPE;
)
AS
BEGIN
    P_OUT_CURSOR := FN_OBTENER_EMPLEADO_POR_ID(P_IN_EMP_Codigo);
END;
/