CREATE OR REPLACE FUNCTION FN_OBTENER_DEDUCCIONES_POR_EMPLEADO(
    P_IN_EMP_CODIGO NMI_EMPLEADO.EMP_CODIGO%TYPE
)
RETURN SYS_REFCURSOR
IS
    CUR_REGISTROS SYS_REFCURSOR;
BEGIN
    OPEN CUR_REGISTROS FOR
SELECT  EP.EMP_CODIGO, EP.EPU_CODIGO, DE.DEM_CODIGO, DEM_ESTADO, TD.TDE_CODIGO, TD.TDE_NOMBRE, TD.TDE_DESCRIPCION,
        TD.TDE_MONTO, TD.TDE_PORCENTAJE, TD.TDE_ESTADO
FROM
    NMI_TIPO_DEDUCCIONES TD,
    NMI_DEDUCCION_EMPLEADO DE,
    NMI_EMPLEADO_PUESTO EP
WHERE
    TD.TDE_CODIGO = DE.TDE_CODIGO AND
    DE.EPU_CODIGO = EP.EPU_CODIGO AND
    TD.TDE_ESTADO = 1 AND
    EP.EMP_CODIGO = P_IN_EMP_CODIGO AND
    EP.EPU_ESTADO = 1;
RETURN CUR_REGISTROS;
END;
/