CREATE OR REPLACE FUNCTION FN_OBTENER_DEDUCCIONES_QUE_NO_TIENE_EMPLEADO (
    P_IN_EMP_CODIGO NMI_EMPLEADO.EMP_CODIGO%TYPE
)
RETURN SYS_REFCURSOR
IS
    CUR_REGISTROS SYS_REFCURSOR;
BEGIN
    OPEN CUR_REGISTROS FOR
SELECT TDE.TDE_CODIGO, TDE.TDE_NOMBRE, TDE.TDE_DESCRIPCION,
       TDE.TDE_MONTO, TDE.TDE_PORCENTAJE, TDE.TDE_ESTADO
FROM NMI_TIPO_DEDUCCIONES TDE
WHERE TDE.TDE_CODIGO NOT IN (
    SELECT  TD.TDE_CODIGO
    FROM
        NMI_TIPO_DEDUCCIONES TD,
        NMI_DEDUCCION_EMPLEADO DE,
        NMI_EMPLEADO_PUESTO EP
    WHERE
        TD.TDE_CODIGO = DE.TDE_CODIGO AND
        DE.EPU_CODIGO = EP.EPU_CODIGO AND
        TD.TDE_ESTADO = 1 AND
        EP.EMP_CODIGO = P_IN_EMP_CODIGO AND
        EP.EPU_ESTADO = 1
) AND
    TDE.TDE_ESTADO = 1;

RETURN CUR_REGISTROS;
END;
/