CREATE OR REPLACE FUNCTION FN_OBTENER_DEDUCCION_POR_ID_DE_EMPLEADO(
    P_IN_EMP_CODIGO NMI_EMPLEADO.EMP_CODIGO%TYPE,
    P_IN_TDE_CODIGO NMI_DEDUCCION_EMPLEADO.TDE_CODIGO%TYPE
)
RETURN SYS_REFCURSOR
IS
    CUR_REGISTROS SYS_REFCURSOR;
BEGIN
    OPEN CUR_REGISTROS FOR
          SELECT EP.EMP_CODIGO
          FROM  NMI_EMPLEADO_PUESTO EP,
                NMI_DEDUCCION_EMPLEADO DE
          WHERE EP.EPU_CODIGO = DE.EPU_CODIGO AND
                EP.EMP_CODIGO = P_IN_EMP_CODIGO AND
                DE.TDE_CODIGO = P_IN_TDE_CODIGO AND
                DE.DEM_ESTADO = 1;
    RETURN CUR_REGISTROS;
END;
/
