CREATE OR REPLACE PROCEDURE PA_NMI_DEDUCCION_EMPLEADO_ELIMINAR (
    P_IN_CODIGO IN NMI_DEDUCCION_EMPLEADO.DEM_CODIGO%TYPE
)
AS
BEGIN
SAVEPOINT PS_AN_ELIMINAR_DEDUCCION_EMPLEADO ;

DELETE FROM NMI_DEDUCCION_EMPLEADO WHERE DEM_CODIGO = P_IN_CODIGO;

COMMIT;
EXCEPTION
    WHEN OTHERS THEN
ROLLBACK TO  PS_AN_ELIMINAR_DEDUCCION_EMPLEADO;
END;
/