CREATE OR REPLACE PROCEDURE PA_OBTENER_DEDUCCION_POR_ID_DE_EMPLEADO(
    P_IN_EMP_CODIGO NMI_EMPLEADO.EMP_CODIGO%TYPE,
    P_IN_TDE_CODIGO NMI_DEDUCCION_EMPLEADO.TDE_CODIGO%TYPE,
    P_OUT_CURSOR OUT SYS_REFCURSOR
  )
AS
BEGIN
    P_OUT_CURSOR := FN_OBTENER_DEDUCCION_POR_ID_DE_EMPLEADO(P_IN_EMP_CODIGO,P_IN_TDE_CODIGO);
END;
/
