CREATE OR REPLACE FUNCTION FN_OBTENER_LISTADO_BONIFICACION(
    P_IN_SEARCH IN VARCHAR2,
    P_IN_SIZE IN NUMBER,
    P_IN_PAGE IN NUMBER
)
    RETURN SYS_REFCURSOR
    IS
    CUR_REGISTROS SYS_REFCURSOR;
V_NEW_PAGE    NUMBER := 0;
BEGIN
    V_NEW_PAGE := P_IN_PAGE * P_IN_SIZE;
OPEN CUR_REGISTROS FOR
SELECT
    BON_CODIGO,
    BON_NOMBRE,
    BON_DESCRIPCION,
    BON_MONTO,
    BON_PORCENTAJE,
    BON_ESTADO
FROM NMI_BONIFICACION
WHERE (P_IN_SEARCH IS NULL OR UPPER(BON_CODIGO) LIKE '%' || UPPER(P_IN_SEARCH) || '%')
   OR (P_IN_SEARCH IS NULL OR UPPER(BON_NOMBRE) LIKE '%' || UPPER(P_IN_SEARCH) || '%')
   OR (P_IN_SEARCH IS NULL OR UPPER(BON_DESCRIPCION) LIKE '%' || UPPER(P_IN_SEARCH) || '%')
   OR (P_IN_SEARCH IS NULL OR UPPER(BON_MONTO) LIKE '%' || UPPER(P_IN_SEARCH) || '%')
   OR (P_IN_SEARCH IS NULL OR UPPER(BON_PORCENTAJE) LIKE '%' || UPPER(P_IN_SEARCH) || '%')
ORDER BY BON_CODIGO
    OFFSET V_NEW_PAGE ROWS FETCH NEXT P_IN_SIZE ROWS ONLY;
RETURN CUR_REGISTROS;
END;
/