CREATE OR REPLACE FUNCTION FN_OBTENER_BONIFICACIONES
              RETURN SYS_REFCURSOR
IS
        CUR_REGISTROS SYS_REFCURSOR;
BEGIN
    OPEN CUR_REGISTROS FOR
SELECT
    BON_CODIGO,
    BON_NOMBRE,
    BON_DESCRIPCION,
    BON_MONTO,
    BON_PORCENTAJE,
    BON_ESTADO
FROM NMI_BONIFICACION
ORDER BY BON_CODIGO;
RETURN CUR_REGISTROS;
END;
/