CREATE OR REPLACE FUNCTION FN_OBTENER_TOTAL_ELEMENTOS_BONIFICACION(
    P_IN_SEARCH IN VARCHAR2
)
    RETURN NUMBER
    IS
    TOTAL_ELEMENTS NUMBER := 0;
BEGIN
SELECT COUNT(*)
INTO TOTAL_ELEMENTS
FROM NMI_BONIFICACION
WHERE (P_IN_SEARCH IS NULL OR UPPER(BON_CODIGO) LIKE '%' || UPPER(P_IN_SEARCH) || '%')
   OR (P_IN_SEARCH IS NULL OR UPPER(BON_NOMBRE) LIKE '%' || UPPER(P_IN_SEARCH) || '%')
   OR (P_IN_SEARCH IS NULL OR UPPER(BON_DESCRIPCION) LIKE '%' || UPPER(P_IN_SEARCH) || '%')
   OR (P_IN_SEARCH IS NULL OR UPPER(BON_MONTO) LIKE '%' || UPPER(P_IN_SEARCH) || '%')
   OR (P_IN_SEARCH IS NULL OR UPPER(BON_PORCENTAJE) LIKE '%' || UPPER(P_IN_SEARCH) || '%');
RETURN TOTAL_ELEMENTS;
END;
/