CREATE OR REPLACE PROCEDURE PA_NMI_BONIFICACION_ACTUALIZAR (
    P_IN_CODIGO IN NMI_BONIFICACION.BON_CODIGO%TYPE,
    P_IN_NOMBRE IN NMI_BONIFICACION.BON_NOMBRE%TYPE,
    P_IN_DESCRIPCION IN NMI_BONIFICACION.BON_DESCRIPCION%TYPE,
    P_IN_MONTO IN NMI_BONIFICACION.BON_MONTO%TYPE,
    P_IN_PORCENTAJE IN NMI_BONIFICACION.BON_PORCENTAJE%TYPE,
    P_IN_ESTADO IN NMI_BONIFICACION.BON_ESTADO%TYPE
)
AS
BEGIN
    SAVEPOINT PS_AN_ACTUALIZAR_BONIFICACION  ;
    
    UPDATE NMI_BONIFICACION SET BON_NOMBRE = P_IN_NOMBRE, BON_DESCRIPCION = P_IN_DESCRIPCION, BON_MONTO = P_IN_MONTO,
        BON_PORCENTAJE = P_IN_PORCENTAJe, BON_ESTADO = P_IN_ESTADO 
    WHERE BON_Codigo = P_IN_CODIGO;
    
    COMMIT;
EXCEPTION 
    WHEN OTHERS THEN
        ROLLBACK TO PS_AN_ACTUALIZAR_BONIFICACION ;
END;
/
