CREATE OR REPLACE PROCEDURE PA_OBTENER_BONIFICACION_POR_ID(
    P_OUT_CURSOR OUT SYS_REFCURSOR,
    P_IN_BON_CODIGO IN NMI_BONIFICACION.BON_CODIGO%TYPE
)
AS
BEGIN
    P_OUT_CURSOR := FN_OBTENER_BONIFICACION_POR_ID(P_IN_BON_CODIGO);
END;
/