CREATE OR REPLACE FUNCTION FN_OBTENER_VENTA(
    P_IN_FECHA_INICIO IN VARCHAR,
    P_IN_FECHA_FINAL IN VARCHAR
)
    RETURN SYS_REFCURSOR
    IS
    CUR_REGISTROS SYS_REFCURSOR;
BEGIN
OPEN CUR_REGISTROS FOR
SELECT
    VEN_CODIGO,
    EPU_CODIGO,
    VEN_MONTO,
    VEN_FECHA
FROM NMI_VENTA
WHERE VEN_FECHA BETWEEN TO_TIMESTAMP(P_IN_FECHA_INICIO, 'DD-MM-YYYY')
          AND TO_TIMESTAMP(P_IN_FECHA_FINAL, 'DD-MM-YYYY');
RETURN CUR_REGISTROS;
END;
/
