CREATE OR REPLACE FUNCTION FN_OBTENER_TODO_TIPOS_AUSENCIA
    RETURN SYS_REFCURSOR
    IS
    CUR_REGISTROS SYS_REFCURSOR;
BEGIN
OPEN CUR_REGISTROS FOR
SELECT TAU_CODIGO,
       TAU_NOMBRE,
       TAU_DESCRIPCION,
       TAU_GOCE_SALARIO
FROM NMI_TIPO_AUSENCIA;
RETURN CUR_REGISTROS;
END;
/


