CREATE OR REPLACE FUNCTION FN_OBTENER_TIPO_AUSENCIA_POR_ID(
    P_IN_TAU_CODIGO IN NMI_TIPO_AUSENCIA.TAU_CODIGO%TYPE
)
    RETURN SYS_REFCURSOR
    IS
    CUR_REGISTROS SYS_REFCURSOR;
BEGIN
OPEN CUR_REGISTROS FOR
SELECT TAU_CODIGO,
       TAU_NOMBRE,
       TAU_DESCRIPCION,
       TAU_GOCE_SALARIO
FROM NMI_TIPO_AUSENCIA
WHERE TAU_CODIGO = P_IN_TAU_CODIGO;
RETURN CUR_REGISTROS;
END;
/

