CREATE OR REPLACE PROCEDURE PA_NMI_TIPO_AUSENCIA_ELIMINAR(P_IN_TAU_CODIGO IN NMI_TIPO_AUSENCIA.TAU_CODIGO%TYPE) IS
BEGIN
SAVEPOINT PS_NMI_TIPO_AUSENCIA_ELIMINAR;
DELETE FROM NMI_TIPO_AUSENCIA WHERE TAU_CODIGO = P_IN_TAU_CODIGO;
COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK TO SAVEPOINT PS_NMI_TIPO_AUSENCIA_ELIMINAR;
END PA_NMI_TIPO_AUSENCIA_ELIMINAR;
/