CREATE OR REPLACE PROCEDURE PA_NMI_TIPO_AUSENCIA_GUARDAR(
    P_IN_TAU_NOMBRE IN NMI_TIPO_AUSENCIA.TAU_NOMBRE%TYPE,
    P_IN_TAU_DESCRIPCION IN NMI_TIPO_AUSENCIA.TAU_DESCRIPCION%TYPE,
    P_IN_TAU_GOCE_SALARIO IN NMI_TIPO_AUSENCIA.TAU_GOCE_SALARIO%TYPE,
    P_OUT_TAU_CODIGO OUT NMI_TIPO_AUSENCIA.TAU_CODIGO%TYPE
) IS
BEGIN
SAVEPOINT PS_AN_TIPO_AUSENCIA_GUARDAR;
INSERT INTO NMI_TIPO_AUSENCIA(TAU_NOMBRE, TAU_DESCRIPCION, TAU_GOCE_SALARIO)
VALUES (P_IN_TAU_NOMBRE, P_IN_TAU_DESCRIPCION, P_IN_TAU_GOCE_SALARIO)
    RETURNING TAU_CODIGO INTO P_OUT_TAU_CODIGO;
COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK TO SAVEPOINT PS_AN_TIPO_AUSENCIA_GUARDAR;
END PA_NMI_TIPO_AUSENCIA_GUARDAR;
/