CREATE OR REPLACE FUNCTION FN_OBTENER_TOTAL_ELEMENTOS_PUESTO(
    P_IN_SEARCH IN VARCHAR2
)
    RETURN NUMBER
    IS
    TOTAL_ELEMENTS NUMBER := 0;
BEGIN
    SELECT COUNT(*)
    INTO TOTAL_ELEMENTS
    FROM NMI_PUESTO
    WHERE (P_IN_SEARCH IS NULL OR PUE_CODIGO LIKE '%' || UPPER(P_IN_SEARCH) || '%')
       OR (P_IN_SEARCH IS NULL OR PUE_NOMBRE LIKE '%' || UPPER(P_IN_SEARCH) || '%')
       OR (P_IN_SEARCH IS NULL OR PUE_DESCRIPCION LIKE '%' || UPPER(P_IN_SEARCH) || '%');
    RETURN TOTAL_ELEMENTS;
END;
/

