CREATE OR REPLACE FUNCTION FN_OBTENER_TODO_PUESTOS
    RETURN SYS_REFCURSOR
    IS
    CUR_REGISTROS SYS_REFCURSOR;
BEGIN
    OPEN CUR_REGISTROS FOR
        SELECT PUE_CODIGO,
               DEP_CODIGO,
               PUE_NOMBRE,
               PUE_DESCRIPCION,
               PUE_ESTADO
        FROM NMI_PUESTO;
    RETURN CUR_REGISTROS;
END;
/


