CREATE OR REPLACE FUNCTION FN_OBTENER_PUESTO_POR_ID(
    P_IN_PUE_CODIGO IN NMI_PUESTO.PUE_CODIGO%TYPE
)
    RETURN SYS_REFCURSOR
    IS
    CUR_REGISTROS SYS_REFCURSOR;
BEGIN
    OPEN CUR_REGISTROS FOR
        SELECT PUE_CODIGO,
               DEP_CODIGO,
               PUE_NOMBRE,
               PUE_DESCRIPCION,
               PUE_ESTADO
        FROM NMI_PUESTO
        WHERE PUE_CODIGO = P_IN_PUE_CODIGO;
    RETURN CUR_REGISTROS;
END;
/

