CREATE OR REPLACE PROCEDURE PA_NMI_PUESTO_ELIMINAR(P_IN_PUE_CODIGO IN NMI_PUESTO.PUE_CODIGO%TYPE) IS
BEGIN
SAVEPOINT PS_NMI_PUESTO_ELIMINAR;
DELETE FROM NMI_PUESTO WHERE PUE_CODIGO = P_IN_PUE_CODIGO;
COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK TO SAVEPOINT PS_NMI_PUESTO_ELIMINAR;
END PA_NMI_PUESTO_ELIMINAR;
/