CREATE OR REPLACE PROCEDURE PA_NMI_PUESTO_ACTUALIZAR(
    P_IN_PUE_CODIGO IN NMI_PUESTO.PUE_CODIGO%TYPE,
    P_IN_DEP_CODIGO IN NMI_PUESTO.DEP_CODIGO%TYPE,
    P_IN_PUE_NOMBRE IN NMI_PUESTO.PUE_NOMBRE%TYPE,
    P_IN_PUE_DESCRIPCION IN NMI_PUESTO.PUE_DESCRIPCION%TYPE,
    P_IN_PUE_ESTADO IN NMI_PUESTO.PUE_ESTADO%TYPE
) IS
BEGIN
SAVEPOINT PS_NMI_PUESTO_ACTUALIZAR;
UPDATE NMI_PUESTO
SET DEP_CODIGO = P_IN_DEP_CODIGO,
    PUE_NOMBRE = P_IN_PUE_NOMBRE,
    PUE_DESCRIPCION = P_IN_PUE_DESCRIPCION,
    PUE_ESTADO = P_IN_PUE_ESTADO
WHERE PUE_CODIGO = P_IN_PUE_CODIGO;
COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK TO SAVEPOINT PS_NMI_PUESTO_ACTUALIZAR;
END PA_NMI_PUESTO_ACTUALIZAR;
/