CREATE OR REPLACE PROCEDURE PA_OBTENER_PUESTO_POR_ID(
    P_OUT_CURSOR OUT SYS_REFCURSOR,
    P_IN_PUE_CODIGO IN NMI_PUESTO.DEP_CODIGO%TYPE
)
AS
BEGIN
    P_OUT_CURSOR := FN_OBTENER_PUESTO_POR_ID(P_IN_PUE_CODIGO);
END;
