CREATE OR REPLACE FUNCTION FN_OBTENER_HORAS_EXTRA_POR_EMPLEADO(
    P_IN_EMP_CODIGO IN NMI_EMPLEADO.EMP_CODIGO%TYPE,
    P_IN_FECHA_INICIO IN VARCHAR,
    P_IN_FECHA_FINAL IN VARCHAR
)
    RETURN SYS_REFCURSOR
    IS
    CUR_REGISTROS SYS_REFCURSOR;
BEGIN
    OPEN CUR_REGISTROS FOR
        SELECT E.EMP_PRIMER_NOMBRE,
               E.EMP_SEGUNDO_NOMBRE,
               E.EMP_PRIMER_APELLIDO,
               E.EMP_SEGUNDO_APELLIDO,
               HE.HEX_CANTIDAD,
               HE.HEX_FECHA,
               HE.HEX_CODIGO
        FROM NMI_EMPLEADO E
                 JOIN NMI_EMPLEADO_PUESTO EP ON E.EMP_CODIGO = EP.EMP_CODIGO
                 JOIN NMI_HORAS_EXTRA HE ON EP.EPU_CODIGO = HE.EPU_CODIGO
        WHERE E.EMP_CODIGO = P_IN_EMP_CODIGO
          AND HE.HEX_FECHA BETWEEN TO_TIMESTAMP(P_IN_FECHA_INICIO, 'DD-MM-YYYY')
            AND TO_TIMESTAMP(P_IN_FECHA_FINAL, 'DD-MM-YYYY');
    RETURN CUR_REGISTROS;
END;
/
