CREATE OR REPLACE FUNCTION FN_OBTENER_HORAS_EXTRA(
    P_IN_FECHA_INICIO IN VARCHAR,
    P_IN_FECHA_FINAL IN VARCHAR
)
    RETURN SYS_REFCURSOR
    IS
    CUR_REGISTROS SYS_REFCURSOR;
BEGIN
    OPEN CUR_REGISTROS FOR
    SELECT * FROM NMI_HORAS_EXTRA
        WHERE HEX_FECHA BETWEEN TO_TIMESTAMP(P_IN_FECHA_INICIO, 'DD-MM-YYYY')
            AND TO_TIMESTAMP(P_IN_FECHA_FINAL, 'DD-MM-YYYY');
    RETURN CUR_REGISTROS;
END;
/
