CREATE OR REPLACE PROCEDURE PA_NMI_HORAS_EXTRA_GUARDAR(
    P_IN_EMP_CODIGO IN NMI_EMPLEADO.EMP_CODIGO%TYPE,
    P_IN_HEX_CANTIDAD IN NMI_HORAS_EXTRA.HEX_CANTIDAD%TYPE,
    P_IN_HEX_FECHA IN VARCHAR,
    P_OUT_HEX_CODIGO OUT NMI_HORAS_EXTRA.HEX_CODIGO%TYPE
) AS
    V_EMPLEADO_PUESTO NMI_EMPLEADO_PUESTO.EPU_CODIGO%TYPE;
BEGIN
    SAVEPOINT PS_AN_HORAS_EXTRA_GUARDAR;

    SELECT EPU_CODIGO INTO V_EMPLEADO_PUESTO
        FROM NMI_EMPLEADO_PUESTO
            WHERE EMP_CODIGO = P_IN_EMP_CODIGO
                AND ROWNUM = 1;

    INSERT INTO NMI_HORAS_EXTRA (EPU_CODIGO, HEX_CANTIDAD, HEX_FECHA)
        VALUES (V_EMPLEADO_PUESTO, P_IN_HEX_CANTIDAD, TO_TIMESTAMP(P_IN_HEX_FECHA, 'DD-MM-YYYY'))
            RETURNING HEX_CODIGO INTO P_OUT_HEX_CODIGO;

    COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
            ROLLBACK TO SAVEPOINT PS_AN_HORAS_EXTRA_GUARDAR;
END PA_NMI_HORAS_EXTRA_GUARDAR;
/
