CREATE OR REPLACE PROCEDURE PA_OBTENER_HORAS_EXTRA_POR_EMPLEADO(
    P_OUT_CURSOR OUT SYS_REFCURSOR,
    P_IN_EMP_CODIGO IN NMI_EMPLEADO.EMP_CODIGO%TYPE,
    P_IN_FECHA_INICIO IN VARCHAR,
    P_IN_FECHA_FINAL IN VARCHAR
)
AS
BEGIN
    P_OUT_CURSOR := FN_OBTENER_HORAS_EXTRA_POR_EMPLEADO(P_IN_EMP_CODIGO, P_IN_FECHA_INICIO, P_IN_FECHA_FINAL);
END;
