CREATE OR REPLACE FUNCTION FN_OBTENER_TODO_OTROS_INGRESOS
              RETURN SYS_REFCURSOR
IS
        CUR_REGISTROS SYS_REFCURSOR;
BEGIN
    OPEN CUR_REGISTROS FOR
SELECT
    O.OIN_CODIGO,
    O.EPU_CODIGO,
    O.OIN_MONTO,
    O.OIN_FECHA,
    EP.EMP_CODIGO,
    E.EMP_PRIMER_NOMBRE,
    E.EMP_PRIMER_APELLIDO
FROM NMI_OTRO_INGRESO O INNER JOIN
     NMI_EMPLEADO_PUESTO EP ON O.EPU_CODIGO = EP.EPU_CODIGO
                        INNER JOIN NMI_EMPLEADO E ON EP.EMP_CODIGO = E.EMP_CODIGO
WHERE EP.EPU_ESTADO = 1
ORDER BY O.OIN_CODIGO;
RETURN CUR_REGISTROS;
END;
/