CREATE OR REPLACE PROCEDURE PA_NMI_OTRO_INGRESO_ACTUALIZAR (
    P_IN_CODIGO IN NMI_OTRO_INGRESO.OIN_CODIGO%TYPE,
    P_IN_EPU_CODIGO IN NMI_OTRO_INGRESO.EPU_CODIGO%TYPE,
    P_IN_MONTO IN NMI_OTRO_INGRESO.OIN_MONTO%TYPE,
    P_IN_FECHA IN VARCHAR
)
AS
BEGIN
    SAVEPOINT PS_AN_ACTUALIZAR_OTRO_INGRESO;
    
    UPDATE NMI_OTRO_INGRESO SET EPU_CODIGO = P_IN_EPU_CODIGO, OIN_MONTO = P_IN_MONTO, OIN_FECHA = TO_TIMESTAMP(P_IN_FECHA, 'DD-MM-YYYY')
    WHERE OIN_CODIGO = P_IN_CODIGO;
    
    COMMIT;
EXCEPTION 
    WHEN OTHERS THEN
        ROLLBACK TO PS_AN_ACTUALIZAR_OTRO_INGRESO;
END;
/
