CREATE OR REPLACE PROCEDURE PA_NMI_OTRO_INGRESO_INSERTAR (
    P_IN_EPU_CODIGO IN NMI_OTRO_INGRESO.EPU_CODIGO%TYPE,
    P_IN_MONTO IN NMI_OTRO_INGRESO.OIN_MONTO%TYPE,
    P_IN_FECHA IN VARCHAR,
    P_OUT_CODIGO OUT NMI_OTRO_INGRESO.OIN_CODIGO%TYPE
)
AS
BEGIN
    SAVEPOINT PS_AN_INSERTAR_OTRO_INGRESO;
    
    INSERT INTO NMI_OTRO_INGRESO (EPU_CODIGO,OIN_MONTO,OIN_FECHA)
        VALUES(P_IN_EPU_CODIGO,P_IN_MONTO,TO_TIMESTAMP(P_IN_FECHA, 'DD-MM-YYYY'))
        RETURNING OIN_CODIGO INTO P_OUT_CODIGO;
    
    COMMIT;
EXCEPTION 
    WHEN OTHERS THEN
        ROLLBACK TO PS_AN_INSERTAR_OTRO_INGRESO;
END;
/
