CREATE OR REPLACE PROCEDURE PA_OBTENER_OTRO_INGRESO_POR_ID(
    P_OUT_CURSOR OUT SYS_REFCURSOR,
    P_IN_OIN_CODIGO IN NMI_OTRO_INGRESO.OIN_CODIGO%TYPE
)
AS
BEGIN
    P_OUT_CURSOR := FN_OBTENER_OTRO_INGRESO_POR_ID(P_IN_OIN_CODIGO);
END;
/