CREATE OR REPLACE FUNCTION FN_OBTENER_PRESTAMOS(
    P_IN_FECHA_INICIO IN VARCHAR,
    P_IN_FECHA_FINAL IN VARCHAR
)
    RETURN SYS_REFCURSOR
    IS
    CUR_REGISTROS SYS_REFCURSOR;
BEGIN
    OPEN CUR_REGISTROS FOR
    SELECT
        PRE_CODIGO,
        EPU_CODIGO,
        PRE_MONTO,
        PRE_INTERES,
        PRE_CANTIDAD_MESES,
        PRE_CUOTA_MENSUAL,
        PRE_DESCRIPCION,
        PRE_MONTO_PAGADO,
        PRE_FECHA_INICIO
    FROM NMI_PRESTAMO
        WHERE PRE_FECHA_INICIO BETWEEN TO_TIMESTAMP(P_IN_FECHA_INICIO, 'DD-MM-YYYY')
              AND TO_TIMESTAMP(P_IN_FECHA_FINAL, 'DD-MM-YYYY');
    RETURN CUR_REGISTROS;
END;
/
