CREATE OR REPLACE PROCEDURE PA_NMI_PRESTAMO_GUARDAR(
    P_IN_EMP_CODIGO IN NMI_EMPLEADO.EMP_CODIGO%TYPE,
    P_IN_PRE_MONTO IN NMI_PRESTAMO.PRE_MONTO%TYPE,
    P_IN_PRE_INTERES IN NMI_PRESTAMO.PRE_INTERES%TYPE,
    P_IN_PRE_CANTIDAD_MESES IN NMI_PRESTAMO.PRE_CANTIDAD_MESES%TYPE,
    P_IN_PRE_DESCRIPCION IN NMI_PRESTAMO.PRE_DESCRIPCION%TYPE,
    P_OUT_PRE_CODIGO OUT NMI_PRESTAMO.PRE_CODIGO%TYPE
) AS
    V_EMPLEADO_PUESTO NMI_EMPLEADO_PUESTO.EPU_CODIGO%TYPE;
    V_CUOTA_MENSUAL NUMBER;
BEGIN
    SAVEPOINT PS_AN_PRESTAMO_GUARDAR;

    SELECT EPU_CODIGO INTO V_EMPLEADO_PUESTO
        FROM NMI_EMPLEADO_PUESTO
            WHERE EMP_CODIGO = P_IN_EMP_CODIGO
                AND ROWNUM = 1;

    V_CUOTA_MENSUAL := P_IN_PRE_MONTO * ( (P_IN_PRE_INTERES / 1200) * POWER(1 + P_IN_PRE_INTERES / 1200, P_IN_PRE_CANTIDAD_MESES) ) / ( POWER(1 + P_IN_PRE_INTERES / 1200, P_IN_PRE_CANTIDAD_MESES) - 1 );

    INSERT INTO NMI_PRESTAMO(EPU_CODIGO, PRE_MONTO, PRE_INTERES, PRE_CANTIDAD_MESES, PRE_CUOTA_MENSUAL, PRE_DESCRIPCION)
        VALUES (V_EMPLEADO_PUESTO, P_IN_PRE_MONTO, P_IN_PRE_INTERES, P_IN_PRE_CANTIDAD_MESES, V_CUOTA_MENSUAL, P_IN_PRE_DESCRIPCION)
            RETURNING PRE_CODIGO INTO P_OUT_PRE_CODIGO;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK TO SAVEPOINT PS_AN_PRESTAMO_GUARDAR;
END PA_NMI_PRESTAMO_GUARDAR;
/
