CREATE OR REPLACE FUNCTION FN_OBTENER_TIPO_DESCUENTO_POR_ID(
    P_IN_TDS_CODIGO IN NMI_TIPO_DESCUENTO.TDS_CODIGO%TYPE
)
    RETURN SYS_REFCURSOR
    IS
    CUR_REGISTROS SYS_REFCURSOR;
BEGIN
OPEN CUR_REGISTROS FOR
SELECT TDS_CODIGO,
       TDS_NOMBRE,
       TDS_DESCRIPCION,
       TDS_MONTO,
       TDS_PORCENTAJE,
       TDS_ESTADO
FROM NMI_TIPO_DESCUENTO
WHERE TDS_CODIGO = P_IN_TDS_CODIGO;
RETURN CUR_REGISTROS;
END;
/

