CREATE OR REPLACE FUNCTION NOMINA.FN_OBTENER_LISTADO_TIPO_DESCUENTO(
    P_IN_SEARCH IN VARCHAR2,
    P_IN_SIZE IN NUMBER,
    P_IN_PAGE IN NUMBER
)
RETURN SYS_REFCURSOR
IS
    CUR_REGISTROS SYS_REFCURSOR;
    V_NEW_PAGE NUMBER := 0;
BEGIN
    V_NEW_PAGE := P_IN_PAGE * P_IN_SIZE;
OPEN CUR_REGISTROS FOR
SELECT
    TDS_CODIGO,
    TDS_NOMBRE,
    TDS_DESCRIPCION,
    TDS_MONTO,
    TDS_PORCENTAJE,
    TDS_ESTADO
FROM NMI_TIPO_DESCUENTO
WHERE
    (P_IN_SEARCH IS NULL OR UPPER(TDS_CODIGO) LIKE '%' || UPPER(P_IN_SEARCH) || '%') OR
    (P_IN_SEARCH IS NULL OR UPPER(TDS_NOMBRE) LIKE '%' || UPPER(P_IN_SEARCH) || '%') OR
    (P_IN_SEARCH IS NULL OR UPPER(TDS_DESCRIPCION) LIKE '%' || UPPER(P_IN_SEARCH) || '%') OR
    (P_IN_SEARCH IS NULL OR UPPER(TDS_MONTO) LIKE '%' || UPPER(P_IN_SEARCH) || '%') OR
    (P_IN_SEARCH IS NULL OR UPPER(TDS_PORCENTAJE) LIKE '%' || UPPER(P_IN_SEARCH) || '%') OR
    (P_IN_SEARCH IS NULL OR UPPER(TDS_ESTADO) LIKE '%' || UPPER(P_IN_SEARCH) || '%')
OFFSET V_NEW_PAGE ROWS
    FETCH NEXT P_IN_SIZE ROWS ONLY;
RETURN CUR_REGISTROS;
END;
/
