CREATE OR REPLACE FUNCTION FN_OBTENER_TODO_TIPOS_DESCUENTO
    RETURN SYS_REFCURSOR
    IS
    CUR_REGISTROS SYS_REFCURSOR;
BEGIN
OPEN CUR_REGISTROS FOR
SELECT TDS_CODIGO,
       TDS_NOMBRE,
       TDS_DESCRIPCION,
       TDS_MONTO,
       TDS_PORCENTAJE,
       TDS_ESTADO
FROM NMI_TIPO_DESCUENTO;
RETURN CUR_REGISTROS;
END;
/


