CREATE OR REPLACE PROCEDURE PA_NMI_TIPO_DESCUENTO_ELIMINAR(P_IN_TDS_CODIGO IN NMI_TIPO_DESCUENTO.TDS_CODIGO%TYPE) IS
BEGIN
SAVEPOINT PS_NMI_TIPO_DESCUENTO_ELIMINAR;
DELETE FROM NMI_TIPO_DESCUENTO WHERE TDS_CODIGO = P_IN_TDS_CODIGO;
COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK TO SAVEPOINT PS_NMI_TIPO_DESCUENTO_ELIMINAR;
END PA_NMI_TIPO_DESCUENTO_ELIMINAR;
/