CREATE OR REPLACE PROCEDURE PA_NMI_TIPO_DESCUENTO_ACTUALIZAR(
    P_IN_TDS_CODIGO IN NMI_TIPO_DESCUENTO.TDS_CODIGO%TYPE,
    P_IN_TDS_NOMBRE IN NMI_TIPO_DESCUENTO.TDS_NOMBRE%TYPE,
    P_IN_TDS_DESCRIPCION IN NMI_TIPO_DESCUENTO.TDS_DESCRIPCION%TYPE,
    P_IN_TDS_MONTO IN NMI_TIPO_DESCUENTO.TDS_MONTO%TYPE,
    P_IN_TDS_PORCENTAJE IN NMI_TIPO_DESCUENTO.TDS_PORCENTAJE%TYPE,
    P_IN_TDS_ESTADO IN NMI_TIPO_DESCUENTO.TDS_ESTADO%TYPE
) IS
BEGIN
SAVEPOINT PS_AN_TIPO_DESCUENTO_ACTUALIZAR;
UPDATE nmi_tipo_descuento
SET
    tds_nombre = P_IN_TDS_NOMBRE,
    tds_descripcion = P_IN_TDS_DESCRIPCION,
    tds_monto = P_IN_TDS_MONTO,
    tds_porcentaje = P_IN_TDS_PORCENTAJE,
    tds_estado = P_IN_TDS_ESTADO
WHERE tds_codigo = P_IN_TDS_CODIGO;
COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK TO SAVEPOINT PS_AN_TIPO_DESCUENTO_ACTUALIZAR;
END PA_NMI_TIPO_DESCUENTO_ACTUALIZAR;
/