CREATE OR REPLACE PROCEDURE PA_NMI_TIPO_DESCUENTO_GUARDAR(
    P_IN_TDS_NOMBRE IN NMI_TIPO_DESCUENTO.TDS_NOMBRE%TYPE,
    P_IN_TDS_DESCRIPCION IN NMI_TIPO_DESCUENTO.TDS_DESCRIPCION%TYPE,
    P_IN_TDS_MONTO IN NMI_TIPO_DESCUENTO.TDS_MONTO%TYPE,
    P_IN_TDS_PORCENTAJE IN NMI_TIPO_DESCUENTO.TDS_PORCENTAJE%TYPE,
    P_IN_TDS_ESTADO IN NMI_TIPO_DESCUENTO.TDS_ESTADO%TYPE,
    P_OUT_TDS_CODIGO OUT NMI_TIPO_DESCUENTO.TDS_CODIGO%TYPE
) IS
BEGIN
SAVEPOINT PS_AN_TIPO_DESCUENTO_GUARDAR;
INSERT INTO NMI_TIPO_DESCUENTO(TDS_NOMBRE, TDS_DESCRIPCION, TDS_MONTO, TDS_PORCENTAJE, TDS_ESTADO)
VALUES (P_IN_TDS_NOMBRE, P_IN_TDS_DESCRIPCION, P_IN_TDS_MONTO, P_IN_TDS_PORCENTAJE, P_IN_TDS_ESTADO)
    RETURNING TDS_CODIGO INTO P_OUT_TDS_CODIGO;
COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK TO SAVEPOINT PS_AN_TIPO_DESCUENTO_GUARDAR;
END PA_NMI_TIPO_DESCUENTO_GUARDAR;
/