CREATE OR REPLACE PROCEDURE PA_OBTENER_TIPO_DESCUENTO_POR_ID(
    P_OUT_CURSOR OUT SYS_REFCURSOR,
    P_IN_TDS_CODIGO IN NMI_TIPO_DESCUENTO.TDS_CODIGO%TYPE
)
AS
BEGIN
    P_OUT_CURSOR := FN_OBTENER_TIPO_DESCUENTO_POR_ID(P_IN_TDS_CODIGO);
END;
