CREATE OR REPLACE FUNCTION FN_OBTENER_NOMBRE_TIPO_DESCUENTO
RETURN SYS_REFCURSOR
IS
    CUR_REGISTROS SYS_REFCURSOR;
BEGIN
    OPEN CUR_REGISTROS FOR
        SELECT  
            TD.TDS_CODIGO,
            TD.TDS_NOMBRE    
        FROM NMI_TIPO_DESCUENTO TD;
    RETURN CUR_REGISTROS;
END;
/
