CREATE OR REPLACE FUNCTION FN_OBTENER_NOMBRE_TIPO_AUSENCIA
RETURN SYS_REFCURSOR
IS
    CUR_REGISTROS SYS_REFCURSOR;
BEGIN
    OPEN CUR_REGISTROS FOR
        SELECT  
            TA.TAU_CODIGO,
            TA.TAU.NOMBRE    
        FROM NMI_TIPO_AUSENCIA TA
    RETURN CUR_REGISTROS;
END;
/
