CREATE OR REPLACE PROCEDURE PA_NMI_AUSENCIA_INSERTAR (
    P_IN_EPU_CODIGO IN NMI_AUSENCIA.EPU_CODIGO%TYPE,
    P_IN_TAU_CODIGO IN NMI_AUSENCIA.TAU_CODIGO%TYPE,
    P_IN_TDS_CODIGO IN NMI_AUSENCIA.TDS_CODIGO%TYPE,
    P_IN_FECHA_SALIDA IN VARCHAR,
    P_IN_FECHA_REGRESO IN VARCHAR,
    P_OUT_CODIGO OUT NMI_AUSENCIA.AUS_CODIGO%TYPE
)
AS
BEGIN
    SAVEPOINT PS_AN_INSERTAR_AUSENCIA;
    
    INSERT INTO NMI_AUSENCIA (EPU_CODIGO, TAU_CODIGO, tds_codigo, aus_fecha_salida, aus_fecha_regreso)
        VALUES(P_IN_EPU_CODIGO,p_in_tau_codigo, P_IN_TDS_CODIGO, TO_TIMESTAMP(P_IN_FECHA_SALIDA, 'DD-MM-YYYY'), TO_TIMESTAMP(P_IN_FECHA_REGRESO, 'DD-MM-YYYY'))
        RETURNING AUS_CODIGO INTO P_OUT_CODIGO;
    
    COMMIT;
EXCEPTION 
    WHEN OTHERS THEN
        ROLLBACK TO PS_AN_INSERTAR_AUSENCIA;
END;
/