CREATE OR REPLACE PROCEDURE PA_NMI_AUSENCIA_ACTUALIZAR (
    P_IN_CODIGO IN NMI_AUSENCIA.AUS_CODIGO%TYPE,
    P_IN_EPU_CODIGO IN NMI_AUSENCIA.EPU_CODIGO%TYPE,
    P_IN_TAU_CODIGO IN NMI_AUSENCIA.TAU_CODIGO%TYPE,
    P_IN_TDS_CODIGO IN NMI_AUSENCIA.TDS_CODIGO%TYPE,
    P_IN_FECHA_SALIDA IN VARCHAR,
    P_IN_FECHA_REGRESO IN VARCHAR
)
AS
BEGIN
    SAVEPOINT PS_AN_ACTUALIZAR_AUSENCIA;
    
    UPDATE NMI_AUSENCIA SET EPU_CODIGO = P_IN_EPU_CODIGO, TAU_CODIGO = P_IN_TAU_CODIGO, TDS_CODIGO= P_IN_TDS_CODIGO, 
                            AUS_FECHA_SALIDA = TO_TIMESTAMP(P_IN_FECHA_SALIDA, 'DD-MM-YYYY'), 
                            AUS_FECHA_REGRESO = TO_TIMESTAMP(P_IN_FECHA_REGRESO, 'DD-MM-YYYY')
    WHERE AUS_CODIGO = P_IN_CODIGO;
    
    COMMIT;
EXCEPTION 
    WHEN OTHERS THEN
        ROLLBACK TO PS_AN_ACTUALIZAR_AUSENCIA;
END;
/
