CREATE OR REPLACE PROCEDURE PA_NMI_AUSENCIA_ELIMINAR (
     P_IN_CODIGO IN NMI_AUSENCIA.AUS_CODIGO%TYPE
)
AS
BEGIN
    SAVEPOINT PS_AN_ELIMINAR_AUSENCIA;
    
    DELETE FROM NMI_AUSENCIA WHERE AUS_CODIGO = P_IN_CODIGO;
    
    COMMIT;
EXCEPTION 
    WHEN OTHERS THEN
        ROLLBACK TO  PS_AN_ELIMINAR_AUSENCIA;
END;
/
