CREATE OR REPLACE PROCEDURE PA_OBTENER_AUSENCIAS_POR_ID(
    P_OUT_CURSOR OUT SYS_REFCURSOR,
    P_IN_AUS_CODIGO IN NMI_AUSENCIA.AUS_CODIGO%TYPE
)
AS
BEGIN
    P_OUT_CURSOR := FN_AUSENCIAS_POR_ID(P_IN_AUS_CODIGO);
END;
/