
CREATE OR REPLACE FUNCTION FN_OBTENER_TODO_TIPO_SUSPENSION
              RETURN SYS_REFCURSOR
IS
        CUR_REGISTROS SYS_REFCURSOR;
BEGIN
    OPEN CUR_REGISTROS FOR
SELECT
    TSU_CODIGO,
    TSU_NOMBRE,
    TSU_DESCRIPCION
FROM NMI_TIPO_SUSPENSION
ORDER BY TSU_CODIGO;
RETURN CUR_REGISTROS;
END;
/