CREATE OR REPLACE FUNCTION FN_OBTENER_TIPO_SUSPENSION_POR_ID(
    P_IN_TSU_CODIGO IN NMI_TIPO_SUSPENSION.TSU_CODIGO%TYPE
)
    RETURN SYS_REFCURSOR
    IS
    CUR_REGISTROS SYS_REFCURSOR;
BEGIN
    OPEN CUR_REGISTROS FOR
SELECT
    TSU_CODIGO,
    TSU_NOMBRE,
    TSU_DESCRIPCION
FROM NMI_TIPO_SUSPENSION
WHERE TSU_CODIGO = P_IN_TSU_CODIGO
ORDER BY TSU_CODIGO;
RETURN CUR_REGISTROS;
END;
/