CREATE OR REPLACE PROCEDURE PA_NMI_TIPO_SUSPENSION_ELIMINAR (
    P_IN_CODIGO IN NMI_TIPO_SUSPENSION.TSU_CODIGO%TYPE
)
AS
BEGIN
    SAVEPOINT PS_AN_ELIMINAR_TIPO_SUSPENSION ;
    
    DELETE FROM NMI_TIPO_SUSPENSION WHERE TSU_CODIGO = P_IN_CODIGO;
    
    COMMIT;
EXCEPTION 
    WHEN OTHERS THEN
        ROLLBACK TO  PS_AN_ELIMINAR_TIPO_SUSPENSION;
END;
/
