CREATE OR REPLACE PROCEDURE PA_NMI_TIPO_SUSPENSION_ACTUALIZAR (
    P_IN_CODIGO IN NMI_TIPO_SUSPENSION.TSU_CODIGO%TYPE,
    P_IN_NOMBRE IN NMI_TIPO_SUSPENSION.TSU_NOMBRE%TYPE,
    P_IN_DESCRIPCION IN NMI_TIPO_SUSPENSION.TSU_DESCRIPCION%TYPE
)
AS
BEGIN
    SAVEPOINT PS_AN_ACTUALIZAR_TIPO_SUSPENSION;
    
    UPDATE NMI_TIPO_SUSPENSION SET TSU_NOMBRE = P_IN_NOMBRE, TSU_DESCRIPCION = P_IN_DESCRIPCION 
    where TSU_CODIGO = P_IN_CODIGO;
    
    COMMIT;
EXCEPTION 
    WHEN OTHERS THEN
        ROLLBACK TO PS_AN_ACTUALIZAR_TIPO_SUSPENSION;
END;
/
