CREATE OR REPLACE PROCEDURE PA_OBTENER_TIPO_SUSPENSION_POR_ID(
    P_OUT_CURSOR OUT SYS_REFCURSOR,
    P_IN_TSU_CODIGO IN NMI_TIPO_SUSPENSION.TSU_CODIGO%TYPE
)
AS
BEGIN
    P_OUT_CURSOR := FN_OBTENER_TIPO_SUSPENSION_POR_ID(P_IN_TSU_CODIGO);
END;
/