CREATE OR REPLACE FUNCTION FN_OBTENER_TOTAL_ELEMENTOS_TIPO_DEDUCCIONES(
    P_IN_SEARCH IN VARCHAR2
)
    RETURN NUMBER
    IS
    TOTAL_ELEMENTS NUMBER := 0;
BEGIN
    SELECT COUNT(*)
    INTO TOTAL_ELEMENTS
    FROM NMI_TIPO_DEDUCCIONES
    WHERE (P_IN_SEARCH IS NULL OR TDE_CODIGO LIKE '%' || UPPER(P_IN_SEARCH) || '%')
       OR (P_IN_SEARCH IS NULL OR TDE_NOMBRE LIKE '%' || UPPER(P_IN_SEARCH) || '%')
       OR (P_IN_SEARCH IS NULL OR TDE_DESCRIPCION LIKE '%' || UPPER(P_IN_SEARCH) || '%')
       OR (P_IN_SEARCH IS NULL OR TDE_MONTO LIKE '%' || UPPER(P_IN_SEARCH) || '%')
       OR (P_IN_SEARCH IS NULL OR TDE_PORCENTAJE LIKE '%' || UPPER(P_IN_SEARCH) || '%')
       OR (P_IN_SEARCH IS NULL OR TDE_ESTADO LIKE '%' || UPPER(P_IN_SEARCH) || '%');
    RETURN TOTAL_ELEMENTS;
END;
/