CREATE OR REPLACE FUNCTION FN_OBTENER_TODO_TIPO_DEDUCCIONES
    RETURN SYS_REFCURSOR
    IS
    CUR_REGISTROS SYS_REFCURSOR;
BEGIN
    OPEN CUR_REGISTROS FOR
        SELECT TDE_CODIGO,
               TDE_NOMBRE,
               TDE_DESCRIPCION,
               TDE_MONTO,
               TDE_PORCENTAJE,
               TDE_ESTADO
        FROM NMI_TIPO_DEDUCCIONES;
    RETURN CUR_REGISTROS;
END;
/


