CREATE OR REPLACE FUNCTION FN_OBTENER_TIPO_DEDUCCIONES_POR_ID(
    P_IN_TDE_CODIGO IN NMI_TIPO_DEDUCCIONES.TDE_CODIGO%TYPE
)
    RETURN SYS_REFCURSOR
    IS
    CUR_REGISTROS SYS_REFCURSOR;
BEGIN
    OPEN CUR_REGISTROS FOR
        SELECT TDE_CODIGO,
               TDE_NOMBRE,
               TDE_DESCRIPCION,
               TDE_MONTO,
               TDE_PORCENTAJE,
               TDE_ESTADO
        FROM NMI_TIPO_DEDUCCIONES
        WHERE TDE_CODIGO = P_IN_TDE_CODIGO;
    RETURN CUR_REGISTROS;
END; /