CREATE OR REPLACE PROCEDURE PA_NMI_TIPO_DEDUCCIONES_ACTUALIZAR(
    P_IN_TDE_CODIGO IN NMI_TIPO_DEDUCCIONES.TDE_CODIGO%TYPE,
    P_IN_TDE_NOMBRE IN NMI_TIPO_DEDUCCIONES.TDE_NOMBRE%TYPE,
    P_IN_TDE_DESCRIPCION IN NMI_TIPO_DEDUCCIONES.TDE_DESCRIPCION%TYPE,
    P_IN_TDE_MONTO IN NMI_TIPO_DEDUCCIONES.TDE_MONTO%TYPE,
    P_IN_TDE_PORCENTAJE IN NMI_TIPO_DEDUCCIONES.TDE_PORCENTAJE%TYPE,
    P_IN_TDE_ESTADO IN NMI_TIPO_DEDUCCIONES.TDE_ESTADO%TYPE
) IS
BEGIN
    SAVEPOINT PS_AN_TIPO_DEDUCCIONES_ACTUALIZAR;
    UPDATE NMI_TIPO_DEDUCCIONES
    SET
        TDE_NOMBRE = P_IN_TDE_NOMBRE,
        TDE_DESCRIPCION = P_IN_TDE_DESCRIPCION,
        TDE_MONTO = P_IN_TDE_MONTO,
        TDE_PORCENTAJE = P_IN_TDE_PORCENTAJE,
        TDE_ESTADO = P_IN_TDE_ESTADO
    WHERE TDE_CODIGO = P_IN_TDE_CODIGO;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK TO SAVEPOINT PS_AN_TIPO_DEDUCCIONES_ACTUALIZAR;
END PA_NMI_TIPO_DEDUCCIONES_ACTUALIZAR;
/