CREATE OR REPLACE PROCEDURE PA_NMI_TIPO_DEDUCCIONES_ELIMINAR(
    P_IN_TDE_CODIGO IN NMI_TIPO_DEDUCCIONES.TDE_CODIGO%TYPE
) IS
BEGIN
    SAVEPOINT PS_AN_TIPO_DEDUCCIONES_ELIMINAR;
    DELETE FROM nmi_TIPO_DEDUCCIONES WHERE tde_codigo = P_IN_TDE_CODIGO;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error al eliminar el tipo de deducciones:');
        ROLLBACK TO SAVEPOINT PS_AN_TIPO_DEDUCCIONES_ELIMINAR;
END PA_NMI_TIPO_DEDUCCIONES_ELIMINAR;
/