CREATE OR REPLACE PROCEDURE PA_NMI_TIPO_DEDUCCIONES_GUARDAR(
    P_IN_TDE_NOMBRE IN NMI_TIPO_DEDUCCIONES.TDE_NOMBRE%TYPE,
    P_IN_TDE_DESCRIPCION IN NMI_TIPO_DEDUCCIONES.TDE_DESCRIPCION%TYPE,
    P_IN_TDE_MONTO IN NMI_TIPO_DEDUCCIONES.TDE_MONTO%TYPE,
    P_IN_TDE_PORCENTAJE IN NMI_TIPO_DEDUCCIONES.TDE_PORCENTAJE%TYPE,
    P_IN_TDE_ESTADO IN NMI_TIPO_DEDUCCIONES.TDE_ESTADO%TYPE,
    P_OUT_TDE_CODIGO OUT NMI_TIPO_DEDUCCIONES.TDE_CODIGO%TYPE
) IS
BEGIN
    SAVEPOINT PS_AN_TIPO_DEDUCCIONES_GUARDAR;
        INSERT INTO nmi_TIPO_DEDUCCIONES (TDE_nombre, TDE_descripcion, TDE_MONTO, TDE_PORCENTAJE, TDE_ESTADO) 
        VALUES (P_IN_TDE_NOMBRE, P_IN_TDE_DESCRIPCION, P_IN_TDE_MONTO, P_IN_TDE_PORCENTAJE, P_IN_TDE_ESTADO)
        RETURNING TDE_codigo INTO P_OUT_TDE_CODIGO;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK TO SAVEPOINT PS_AN_TIPO_DEDUCCIONES_GUARDAR;
END PA_NMI_TIPO_DEDUCCIONES_GUARDAR;
/