CREATE OR REPLACE PROCEDURE PA_OBTENER_TIPO_DEDUCCIONES_POR_ID(
    P_OUT_CURSOR OUT SYS_REFCURSOR,
    P_IN_TDE_CODIGO IN NMI_TIPO_DEDUCCIONES.TDE_CODIGO%TYPE
)
AS
BEGIN
    P_OUT_CURSOR := FN_OBTENER_TIPO_DEDUCCIONES_POR_ID(P_IN_TDE_CODIGO);
END;
/