CREATE OR REPLACE FUNCTION FN_OBTENER_TIPO_PRESTACION_POR_ID(
    P_IN_TPR_CODIGO IN NMI_TIPO_PRESTACION.TPR_CODIGO%TYPE
)
    RETURN SYS_REFCURSOR
    IS
    CUR_REGISTROS SYS_REFCURSOR;
BEGIN
    OPEN CUR_REGISTROS FOR
        SELECT TPR_CODIGO,
               TPR_NOMBRE
        FROM NMI_TIPO_PRESTACION
        WHERE TPR_CODIGO = P_IN_TPR_CODIGO;
    RETURN CUR_REGISTROS;
END; /