CREATE OR REPLACE PROCEDURE PA_NMI_TIPO_PRESTACION_ELIMINAR(
    P_IN_TPR_CODIGO IN NMI_TIPO_PRESTACION.TPR_CODIGO%TYPE
) IS
BEGIN
    SAVEPOINT PS_AN_TIPO_PRESTACION_ELIMINAR;
    DELETE FROM nmi_TIPO_PRESTACION WHERE TPR_codigo = P_IN_TPR_CODIGO;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error al eliminar el tipo de prestacion:');
        ROLLBACK TO SAVEPOINT PS_AN_TIPO_PRESTACION_ELIMINAR;
END PA_NMI_TIPO_PRESTACION_ELIMINAR;
/