CREATE OR REPLACE PROCEDURE PA_NMI_TIPO_PRESTACION_ACTUALIZAR(
    P_IN_TPR_CODIGO IN NMI_TIPO_PRESTACION.TPR_CODIGO%TYPE,
    P_IN_TPR_NOMBRE IN NMI_TIPO_PRESTACION.TPR_NOMBRE%TYPE
) IS
BEGIN
    SAVEPOINT PS_AN_TIPO_PRESTACION_ACTUALIZAR;
    UPDATE nmi_TIPO_PRESTACION
    SET
        TPR_nombre = P_IN_TPR_NOMBRE
    WHERE TPR_codigo = P_IN_TPR_CODIGO;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK TO SAVEPOINT PS_AN_TIPO_PRESTACION_ACTUALIZAR;
END PA_NMI_TIPO_PRESTACION_ACTUALIZAR;
/