CREATE OR REPLACE FUNCTION FN_OBTENER_PRODUCCIONES(
    P_IN_FECHA_INICIO IN VARCHAR,
    P_IN_FECHA_FINAL IN VARCHAR
)
    RETURN SYS_REFCURSOR
    IS
    CUR_REGISTROS SYS_REFCURSOR;
BEGIN
OPEN CUR_REGISTROS FOR
SELECT
    PRO_CODIGO,
    EPU_CODIGO,
    PRO_CANTIDAD,
    PRO_FECHA
FROM NMI_PRODUCCION
WHERE PRO_FECHA BETWEEN TO_TIMESTAMP(P_IN_FECHA_INICIO, 'DD-MM-YYYY')
          AND TO_TIMESTAMP(P_IN_FECHA_FINAL, 'DD-MM-YYYY');
RETURN CUR_REGISTROS;
END;
/
