CREATE OR REPLACE FUNCTION FN_OBTENER_PRODUCCIONES(
    P_IN_FECHA_INICIO IN VARCHAR,
    P_IN_FECHA_FINAL IN VARCHAR
)
    RETURN SYS_REFCURSOR
    IS
    CUR_REGISTROS SYS_REFCURSOR;
BEGIN
OPEN CUR_REGISTROS FOR
    SELECT
        P.PRO_CODIGO,
        P.PRO_CANTIDAD,
        P.PRO_FECHA,
        E.EMP_PRIMER_NOMBRE,
        E.EMP_SEGUNDO_NOMBRE,
        E.EMP_PRIMER_APELLIDO,
        E.EMP_SEGUNDO_APELLIDO
    FROM NMI_EMPLEADO E
             JOIN NMI_EMPLEADO_PUESTO EP ON E.EMP_CODIGO = EP.EMP_CODIGO
             JOIN NMI_PRODUCCION P ON EP.EPU_CODIGO = P.EPU_CODIGO
    WHERE P.PRO_FECHA BETWEEN TO_TIMESTAMP(P_IN_FECHA_INICIO, 'DD-MM-YYYY')
              AND TO_TIMESTAMP(P_IN_FECHA_FINAL, 'DD-MM-YYYY');
RETURN CUR_REGISTROS;
END;
/
