CREATE OR REPLACE PROCEDURE PA_NMI_PRODUCCION_GUARDAR(
    P_IN_EMP_CODIGO IN NMI_EMPLEADO.EMP_CODIGO%TYPE,
    P_IN_PRO_CANTIDAD IN NMI_PRODUCCION.PRO_CANTIDAD%TYPE,
    P_IN_PRO_FECHA IN VARCHAR,
    P_OUT_PRO_CODIGO OUT NMI_PRODUCCION.PRO_CODIGO%TYPE
) AS
    V_EMPLEADO_PUESTO NMI_EMPLEADO_PUESTO.EPU_CODIGO%TYPE;
BEGIN
    SAVEPOINT PS_AN_PRODUCCION_GUARDAR;

    SELECT EPU_CODIGO INTO V_EMPLEADO_PUESTO
        FROM NMI_EMPLEADO_PUESTO
            WHERE EMP_CODIGO = P_IN_EMP_CODIGO
                AND ROWNUM = 1;

    INSERT INTO NMI_PRODUCCION(EPU_CODIGO, PRO_CANTIDAD, PRO_FECHA)
        VALUES (V_EMPLEADO_PUESTO, P_IN_PRO_CANTIDAD, TO_TIMESTAMP(P_IN_PRO_FECHA, 'DD-MM-YYYY'))
            RETURNING PRO_CODIGO INTO P_OUT_PRO_CODIGO;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK TO SAVEPOINT PS_AN_PRODUCCION_GUARDAR;
END PA_NMI_PRODUCCION_GUARDAR;
/
