CREATE OR REPLACE FUNCTION FN_OBTENER_LISTADO_PERIODO(
    P_IN_SEARCH IN VARCHAR2,
    P_IN_SIZE IN NUMBER,
    P_IN_PAGE IN NUMBER
)
RETURN SYS_REFCURSOR
IS
    CUR_REGISTROS SYS_REFCURSOR;
    V_NEW_PAGE NUMBER := 0;
BEGIN
    V_NEW_PAGE := P_IN_PAGE * P_IN_SIZE;
OPEN CUR_REGISTROS FOR
SELECT
    PER_CODIGO,
    PER_NOMBRE,
    PER_FECHA_INICIO,
    PER_FECHA_FINAL,
    PER_FECHA_PAGO
FROM NMI_PERIODO
WHERE
    (P_IN_SEARCH IS NULL OR PER_CODIGO LIKE '%' || UPPER(P_IN_SEARCH) || '%') OR
    (P_IN_SEARCH IS NULL OR PER_NOMBRE LIKE '%' || UPPER(P_IN_SEARCH) || '%') OR
    (P_IN_SEARCH IS NULL OR PER_FECHA_INICIO LIKE '%' || UPPER(P_IN_SEARCH) || '%') OR
    (P_IN_SEARCH IS NULL OR PER_FECHA_FINAL LIKE '%' || UPPER(P_IN_SEARCH) || '%') OR
    (P_IN_SEARCH IS NULL OR PER_FECHA_PAGO LIKE '%' || UPPER(P_IN_SEARCH) || '%')
OFFSET V_NEW_PAGE ROWS
    FETCH NEXT P_IN_SIZE ROWS ONLY;
RETURN CUR_REGISTROS;
END;
/
