CREATE OR REPLACE FUNCTION FN_OBTENER_TOTAL_ELEMENTOS_PERIODO(
    P_IN_SEARCH IN VARCHAR2
)
    RETURN NUMBER
    IS
    TOTAL_ELEMENTS NUMBER := 0;
BEGIN
    SELECT COUNT(*)
    INTO TOTAL_ELEMENTS
    FROM NMI_PERIODO
    WHERE (P_IN_SEARCH IS NULL OR PER_CODIGO LIKE '%' || UPPER(P_IN_SEARCH) || '%')
       OR (P_IN_SEARCH IS NULL OR PER_NOMBRE LIKE '%' || UPPER(P_IN_SEARCH) || '%')
       OR (P_IN_SEARCH IS NULL OR PER_FECHA_INICIO LIKE '%' || UPPER(P_IN_SEARCH) || '%')
       OR (P_IN_SEARCH IS NULL OR PER_FECHA_FINAL LIKE '%' || UPPER(P_IN_SEARCH) || '%')
       OR (P_IN_SEARCH IS NULL OR PER_FECHA_PAGO LIKE '%' || UPPER(P_IN_SEARCH) || '%');
    RETURN TOTAL_ELEMENTS;
END;
/

