CREATE OR REPLACE FUNCTION FN_OBTENER_PERIODO_POR_ID(
    P_IN_PER_CODIGO IN NMI_PERIODO.PER_CODIGO%TYPE
)
    RETURN SYS_REFCURSOR
    IS
    CUR_REGISTROS SYS_REFCURSOR;
BEGIN
OPEN CUR_REGISTROS FOR
SELECT PER_CODIGO,
       PER_NOMBRE,
       PER_FECHA_INICIO,
       PER_FECHA_FINAL,
       PER_FECHA_PAGO
FROM NMI_PERIODO
WHERE PER_CODIGO = P_IN_PER_CODIGO;
RETURN CUR_REGISTROS;
END;
/

