CREATE OR REPLACE FUNCTION FN_OBTENER_TODO_PERIODOS
    RETURN SYS_REFCURSOR
    IS
    CUR_REGISTROS SYS_REFCURSOR;
BEGIN
OPEN CUR_REGISTROS FOR
SELECT PER_CODIGO,
       PER_NOMBRE,
       PER_FECHA_INICIO,
       PER_FECHA_FINAL,
       PER_FECHA_PAGO
FROM NMI_PERIODO;
RETURN CUR_REGISTROS;
END;
/


