CREATE OR REPLACE PROCEDURE PA_NMI_PERIODO_ACTUALIZAR(
    P_IN_PER_CODIGO IN NMI_PERIODO.PER_CODIGO%TYPE,
    P_IN_PER_NOMBRE IN NMI_PERIODO.PER_NOMBRE%TYPE,
    P_IN_PER_FECHA_INICIO IN VARCHAR,
    P_IN_PER_FECHA_FINAL IN VARCHAR,
    P_IN_PER_FECHA_PAGO IN VARCHAR
) IS
BEGIN
SAVEPOINT PS_NMI_PERIODO_ACTUALIZAR;
UPDATE NMI_PERIODO
SET PER_NOMBRE = P_IN_PER_NOMBRE,
    PER_FECHA_INICIO = TO_TIMESTAMP(P_IN_PER_FECHA_INICIO, 'DD-MM-YYYY'),
    PER_FECHA_FINAL = TO_TIMESTAMP(P_IN_PER_FECHA_FINAL, 'DD-MM-YYYY'),
    PER_FECHA_PAGO = TO_TIMESTAMP(P_IN_PER_FECHA_PAGO, 'DD-MM-YYYY')
WHERE PER_CODIGO = P_IN_PER_CODIGO;
COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK TO SAVEPOINT PS_NMI_PERIODO_ACTUALIZAR;
END PA_NMI_PERIODO_ACTUALIZAR;
/