CREATE OR REPLACE PROCEDURE PA_NMI_PERIODO_GUARDAR(
    P_IN_PER_NOMBRE IN NMI_PERIODO.PER_NOMBRE%TYPE,
    P_IN_PER_FECHA_INICIO IN NMI_PERIODO.PER_FECHA_INICIO%TYPE,
    P_IN_PER_FECHA_FINAL IN NMI_PERIODO.PER_FECHA_FINAL%TYPE,
    P_IN_PER_FECHA_PAGO IN NMI_PERIODO.PER_FECHA_PAGO%TYPE,
    P_OUT_PER_CODIGO OUT NMI_PERIODO.PER_CODIGO%TYPE
) IS
BEGIN
SAVEPOINT PS_AN_PERIODO_GUARDAR;
INSERT INTO NMI_PERIODO(PER_NOMBRE, PER_FECHA_INICIO, PER_FECHA_FINAL, PER_FECHA_PAGO)
VALUES (P_IN_PER_NOMBRE, P_IN_PER_FECHA_INICIO, P_IN_PER_FECHA_FINAL, P_IN_PER_FECHA_PAGO)
    RETURNING PER_CODIGO INTO P_OUT_PER_CODIGO;
COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK TO SAVEPOINT PS_AN_PERIODO_GUARDAR;
END PA_NMI_PERIODO_GUARDAR;
/