CREATE OR REPLACE PROCEDURE PA_NMI_PERIODO_ELIMINAR(P_IN_PER_CODIGO IN NMI_PERIODO.PER_CODIGO%TYPE) IS
BEGIN
SAVEPOINT PS_NMI_PERIODO_ELIMINAR;
DELETE FROM NMI_PERIODO WHERE PER_CODIGO = P_IN_PER_CODIGO;
COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK TO SAVEPOINT PS_NMI_PERIODO_ELIMINAR;
END PA_NMI_PERIODO_ELIMINAR;
/