CREATE OR REPLACE PROCEDURE PA_NMI_PERIODO_ACTUALIZAR(
    P_IN_PER_CODIGO IN NMI_PERIODO.PER_CODIGO%TYPE,
    P_IN_PER_NOMBRE IN NMI_PERIODO.PER_NOMBRE%TYPE,
    P_IN_PER_FECHA_INICIO IN NMI_PERIODO.PER_FECHA_INICIO%TYPE,
    P_IN_PER_FECHA_FINAL IN NMI_PERIODO.PER_FECHA_FINAL%TYPE,
    P_IN_PER_FECHA_PAGO IN NMI_PERIODO.PER_FECHA_PAGO%TYPE
) IS
BEGIN
SAVEPOINT PS_NMI_PERIODO_ACTUALIZAR;
UPDATE NMI_PERIODO
SET PER_NOMBRE = P_IN_PER_NOMBRE,
    PER_FECHA_INICIO = P_IN_PER_FECHA_INICIO,
    PER_FECHA_FINAL = P_IN_PER_FECHA_FINAL,
    PER_FECHA_PAGO = P_IN_PER_FECHA_PAGO
WHERE PER_CODIGO = P_IN_PER_CODIGO;
COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK TO SAVEPOINT PS_NMI_PERIODO_ACTUALIZAR;
END PA_NMI_PERIODO_ACTUALIZAR;
/