CREATE OR REPLACE PROCEDURE PA_OBTENER_PERIODO_POR_ID(
    P_OUT_CURSOR OUT SYS_REFCURSOR,
    P_IN_PER_CODIGO IN NMI_PERIODO.PER_CODIGO%TYPE
)
AS
BEGIN
    P_OUT_CURSOR := FN_OBTENER_PERIODO_POR_ID(P_IN_PER_CODIGO);
END;
